import type { CaptainsChallengeCatalogItem } from "@/lib/captainsTypes";

export const captainsDefaultChallengeCatalog: CaptainsChallengeCatalogItem[] = [
  {
    "id": "default-001",
    "title": "Selfie de bienvenida",
    "description": "Haced una selfie de la mesa completa antes de empezar el juego.",
    "evidence_type": "photo",
    "category": "Bienvenida",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-002",
    "title": "Nombre de equipo",
    "description": "Grabad un audio diciendo el nombre oficial de vuestra mesa y vuestro grito de guerra.",
    "evidence_type": "audio",
    "category": "Bienvenida",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-003",
    "title": "Pose de portada",
    "description": "Haced una foto como si vuestra mesa saliera en la portada de una revista.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-004",
    "title": "Foto elegante",
    "description": "Haced una foto mostrando el look más elegante de vuestra mesa.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-005",
    "title": "Todos a una",
    "description": "Haced una foto de toda la mesa haciendo el mismo gesto.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-006",
    "title": "Mesa congelada",
    "description": "Grabad un vídeo de toda la mesa quedándose congelada durante cinco segundos.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-007",
    "title": "Brindis de mesa",
    "description": "Haced una foto de toda la mesa brindando por los novios.",
    "evidence_type": "photo",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-008",
    "title": "Brindis narrado",
    "description": "Grabad un audio con un brindis corto para los novios.",
    "evidence_type": "audio",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-009",
    "title": "La mesa más coordinada",
    "description": "Grabad un vídeo haciendo un movimiento sincronizado entre todos.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-010",
    "title": "Foto con los novios",
    "description": "Conseguid una foto de alguien de la mesa con los novios.",
    "evidence_type": "photo",
    "category": "Novios",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-011",
    "title": "Consejo matrimonial",
    "description": "Grabad un audio con un consejo para los novios.",
    "evidence_type": "audio",
    "category": "Novios",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-012",
    "title": "Mensaje secreto",
    "description": "Grabad un vídeo corto dedicando un mensaje sorpresa a los novios.",
    "evidence_type": "video",
    "category": "Novios",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-013",
    "title": "Recuerdo favorito",
    "description": "Grabad un audio contando un recuerdo bonito con alguno de los novios.",
    "evidence_type": "audio",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-014",
    "title": "La foto más bonita",
    "description": "Capturad un momento bonito de la boda desde vuestra mesa.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-015",
    "title": "Declaración grupal",
    "description": "Grabad un vídeo corto diciendo algo bonito a los novios entre todos.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-016",
    "title": "Abrazo colectivo",
    "description": "Haced una foto de la mesa dándose un abrazo o gesto cariñoso.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-017",
    "title": "Foto en la pista",
    "description": "Haced una foto de alguien de la mesa dándolo todo en la pista de baile.",
    "evidence_type": "photo",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-018",
    "title": "Paso imposible",
    "description": "Grabad un vídeo enseñando el paso de baile más raro de la mesa.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-019",
    "title": "Coreografía express",
    "description": "Grabad una coreografía de diez segundos con al menos tres personas.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-020",
    "title": "DJ por un minuto",
    "description": "Grabad un audio cantando el estribillo de una canción que debería sonar hoy.",
    "evidence_type": "audio",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-021",
    "title": "Aliados de otra mesa",
    "description": "Haced una foto con alguien de otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-022",
    "title": "Intercambio de cumplidos",
    "description": "Grabad un audio diciendo un cumplido a otra mesa.",
    "evidence_type": "audio",
    "category": "Interacción",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-023",
    "title": "Foto con desconocidos",
    "description": "Haced una foto con dos personas invitadas que no estén en vuestra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-024",
    "title": "Reto diplomático",
    "description": "Grabad un vídeo convenciendo a otra mesa para que os anime.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-025",
    "title": "Selfie imposible",
    "description": "Haced una selfie donde salga el mayor número posible de personas de la mesa.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-026",
    "title": "Momento película",
    "description": "Recread una escena dramática o divertida como si fuese una película.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-027",
    "title": "La risa más contagiosa",
    "description": "Grabad un audio con la mejor carcajada de la mesa.",
    "evidence_type": "audio",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-028",
    "title": "Objeto misterioso",
    "description": "Haced una foto del objeto más inesperado que encontréis en la mesa.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-029",
    "title": "Foto de celebración",
    "description": "Haced una foto de la mesa celebrando como si hubiese ganado la Champions.",
    "evidence_type": "photo",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-030",
    "title": "Cántico de campeones",
    "description": "Grabad un audio con un cántico inventado para vuestra mesa.",
    "evidence_type": "audio",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-031",
    "title": "Entrada triunfal",
    "description": "Grabad un vídeo entrando en plano como estrellas de la fiesta.",
    "evidence_type": "video",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-032",
    "title": "Confeti humano",
    "description": "Haced una foto simulando una celebración épica sin usar confeti real.",
    "evidence_type": "photo",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-033",
    "title": "Detalle del lugar",
    "description": "Haced una foto bonita de un detalle de la decoración o del espacio.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-034",
    "title": "La mesa recomienda",
    "description": "Grabad un audio recomendando el mejor momento de la celebración hasta ahora.",
    "evidence_type": "audio",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-035",
    "title": "Mini tour",
    "description": "Grabad un vídeo de diez segundos enseñando vuestro rincón favorito del evento.",
    "evidence_type": "video",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-036",
    "title": "Final de película",
    "description": "Grabad un vídeo de despedida para el resumen final del evento.",
    "evidence_type": "video",
    "category": "Resumen",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-037",
    "title": "Foto de los zapatos",
    "description": "Haced una foto creativa juntando los zapatos de varias personas de la mesa.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-038",
    "title": "Manos arriba",
    "description": "Haced una foto de toda la mesa con las manos arriba como celebración.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-039",
    "title": "Corazones con dedos",
    "description": "Haced una foto formando corazones con las manos para los novios.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-040",
    "title": "La mesa seria",
    "description": "Haced una foto de toda la mesa posando con la cara más seria posible.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-041",
    "title": "La mesa loca",
    "description": "Haced una foto de toda la mesa con la pose más disparatada.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-042",
    "title": "Aplauso sincronizado",
    "description": "Grabad un vídeo de toda la mesa aplaudiendo de forma sincronizada.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-043",
    "title": "Ola de mesa",
    "description": "Grabad un vídeo haciendo una ola de un lado a otro de la mesa.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-044",
    "title": "El brindis silencioso",
    "description": "Grabad un vídeo haciendo un brindis exagerado sin decir una sola palabra.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-045",
    "title": "Retrato del capitán",
    "description": "Haced una foto épica del capitán o capitana de la mesa.",
    "evidence_type": "photo",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-046",
    "title": "El mejor complemento",
    "description": "Haced una foto del complemento más llamativo de la mesa.",
    "evidence_type": "photo",
    "category": "Moda",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-047",
    "title": "Foto con flores",
    "description": "Haced una foto bonita usando flores o decoración floral del evento.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-048",
    "title": "Detalle dulce",
    "description": "Haced una foto del detalle más dulce, bonito o apetecible que encontréis.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-049",
    "title": "La servilleta creativa",
    "description": "Haced una foto usando una servilleta como parte de una composición divertida.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-050",
    "title": "Menú favorito",
    "description": "Grabad un audio defendiendo cuál ha sido o será el mejor plato del evento.",
    "evidence_type": "audio",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-051",
    "title": "Foto de anillos imaginarios",
    "description": "Haced una foto simulando una pedida de mano con anillos imaginarios.",
    "evidence_type": "photo",
    "category": "Novios",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-052",
    "title": "Dedicatoria en audio",
    "description": "Grabad una dedicatoria de máximo treinta segundos para los novios.",
    "evidence_type": "audio",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-053",
    "title": "Canción inventada",
    "description": "Grabad un audio cantando una canción inventada para el evento.",
    "evidence_type": "audio",
    "category": "Audio",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-054",
    "title": "Entrevista express",
    "description": "Grabad un vídeo entrevistando a alguien de la mesa con tres preguntas rápidas.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-055",
    "title": "Pronóstico de futuro",
    "description": "Grabad un audio prediciendo cómo será la vida de los novios dentro de diez años.",
    "evidence_type": "audio",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-056",
    "title": "Receta para el amor",
    "description": "Grabad un audio con vuestra receta de mesa para una relación feliz.",
    "evidence_type": "audio",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-057",
    "title": "Tres palabras para los novios",
    "description": "Grabad un audio donde cada persona diga una palabra para los novios.",
    "evidence_type": "audio",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-058",
    "title": "Imitación cariñosa",
    "description": "Grabad un vídeo haciendo una imitación cariñosa y respetuosa de una escena típica de pareja.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-059",
    "title": "Pregunta relámpago",
    "description": "Grabad un vídeo respondiendo rápido a qué hace única esta celebración.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-060",
    "title": "Minuto de aplausos",
    "description": "Grabad un audio con el aplauso más entusiasta de vuestra mesa.",
    "evidence_type": "audio",
    "category": "Fiesta",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-061",
    "title": "Baile sentado",
    "description": "Grabad un vídeo bailando sin levantarse de la silla.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-062",
    "title": "Zapateado de mesa",
    "description": "Grabad un audio o vídeo haciendo ritmo con los pies bajo la mesa.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-063",
    "title": "Mannequin challenge",
    "description": "Grabad un vídeo de toda la mesa inmóvil como una foto viviente.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-064",
    "title": "Pase de modelos",
    "description": "Grabad un vídeo de tres personas desfilando brevemente junto a la mesa.",
    "evidence_type": "video",
    "category": "Moda",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-065",
    "title": "Vídeo boomerang humano",
    "description": "Grabad un vídeo repitiendo un gesto hacia delante y hacia atrás como un boomerang.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-066",
    "title": "Cámara lenta épica",
    "description": "Grabad un vídeo simulando una escena épica a cámara lenta.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-067",
    "title": "Abrazo a otra mesa",
    "description": "Haced una foto de alguien de vuestra mesa abrazando a alguien de otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-068",
    "title": "Firma de alianza",
    "description": "Haced una foto con dos mesas posando como si acabaran de firmar una alianza.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-069",
    "title": "Foto con alguien de staff",
    "description": "Haced una foto amable con alguien del equipo del evento, si está disponible.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-070",
    "title": "Trueque simbólico",
    "description": "Haced una foto intercambiando un objeto simbólico con otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-071",
    "title": "Embajadores de mesa",
    "description": "Grabad un vídeo presentando vuestra mesa a otra mesa como si fuerais embajadores.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-072",
    "title": "Mensaje de otra mesa",
    "description": "Conseguid que otra mesa grabe un audio animando a vuestro equipo.",
    "evidence_type": "audio",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-073",
    "title": "Foto intergeneracional",
    "description": "Haced una foto con personas de generaciones distintas, si es posible.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-074",
    "title": "Foto de infancia recreada",
    "description": "Recread una foto de infancia imaginaria con poses exageradas.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-075",
    "title": "Mirada al futuro",
    "description": "Haced una foto mirando todos hacia un mismo punto como si vierais el futuro.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-076",
    "title": "Promesa de mesa",
    "description": "Grabad un audio con una promesa divertida que vuestra mesa cumplirá hoy.",
    "evidence_type": "audio",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-077",
    "title": "Brindis emocional",
    "description": "Grabad un vídeo con un brindis emotivo de máximo veinte segundos.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-078",
    "title": "Lágrima de felicidad",
    "description": "Haced una foto interpretando una escena dramática de emoción máxima.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-079",
    "title": "Postal para mañana",
    "description": "Haced una foto que los novios deberían guardar para recordar mañana.",
    "evidence_type": "photo",
    "category": "Resumen",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-080",
    "title": "Foto artística",
    "description": "Haced una foto cuidando encuadre, luz y composición como si fuera de concurso.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-081",
    "title": "Sombra divertida",
    "description": "Haced una foto usando sombras para crear una escena divertida.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-082",
    "title": "Reflejo creativo",
    "description": "Haced una foto usando un reflejo en copa, cristal, espejo o móvil.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-083",
    "title": "Perspectiva imposible",
    "description": "Haced una foto jugando con la perspectiva para crear una ilusión óptica.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-084",
    "title": "Color del evento",
    "description": "Haced una foto donde domine el color principal de la celebración.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-085",
    "title": "Rincón secreto",
    "description": "Haced una foto de un rincón bonito que quizá otros no hayan visto.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-086",
    "title": "Foto minimalista",
    "description": "Haced una foto sencilla y elegante con pocos elementos.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-087",
    "title": "Mini documental",
    "description": "Grabad un vídeo de quince segundos contando qué está pasando en vuestra mesa.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-088",
    "title": "Noticia de última hora",
    "description": "Grabad un vídeo narrando una noticia inventada sobre el evento.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-089",
    "title": "Trailer de la mesa",
    "description": "Grabad un tráiler breve presentando vuestra mesa como si fuera una película.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-090",
    "title": "Tutorial absurdo",
    "description": "Grabad un vídeo explicando un tutorial absurdo relacionado con la fiesta.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-091",
    "title": "Anuncio publicitario",
    "description": "Grabad un vídeo vendiendo vuestra mesa como si fuera el mejor producto del mundo.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-092",
    "title": "Debate serio",
    "description": "Grabad un vídeo debatiendo con máxima seriedad un tema totalmente absurdo.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-093",
    "title": "El objeto talismán",
    "description": "Haced una foto del objeto que representa la suerte de vuestra mesa.",
    "evidence_type": "photo",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-094",
    "title": "Mascota imaginaria",
    "description": "Haced una foto o vídeo presentando la mascota imaginaria de vuestra mesa.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-095",
    "title": "Superhéroes de mesa",
    "description": "Haced una foto posando como superhéroes listos para salvar la fiesta.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-096",
    "title": "Villanos elegantes",
    "description": "Haced una foto posando como villanos de película, pero con elegancia.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-097",
    "title": "La misión secreta",
    "description": "Grabad un audio inventando una misión secreta para los novios.",
    "evidence_type": "audio",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-098",
    "title": "Código de mesa",
    "description": "Grabad un audio diciendo una contraseña secreta inventada por vuestra mesa.",
    "evidence_type": "audio",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-099",
    "title": "El aplausómetro",
    "description": "Grabad un vídeo midiendo quién consigue el aplauso más fuerte de la mesa.",
    "evidence_type": "video",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-100",
    "title": "Cierre de capitanes",
    "description": "Grabad un vídeo final diciendo el nombre de vuestra mesa y despidiéndoos del juego.",
    "evidence_type": "video",
    "category": "Resumen",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  }
];
