import type { CaptainsChallengeCatalogItem } from "@/lib/captainsTypes";

export const captainsDefaultChallengeCatalog: CaptainsChallengeCatalogItem[] = [
  {
    "id": "default-001",
    "title": "Selfie de bienvenida",
    "description": "Haced una selfie de la mesa completa antes de empezar el juego.",
    "evidence_type": "photo",
    "category": "Bienvenida",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-002",
    "title": "Nombre de equipo",
    "description": "Grabad un vídeo diciendo el nombre oficial de vuestra mesa y vuestro grito de guerra.",
    "evidence_type": "video",
    "category": "Bienvenida",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-003",
    "title": "Pose de portada",
    "description": "Haced una foto como si vuestra mesa saliera en la portada de una revista.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-004",
    "title": "Foto elegante",
    "description": "Haced una foto mostrando el look más elegante de vuestra mesa.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-005",
    "title": "Todos a una",
    "description": "Haced una foto de toda la mesa haciendo el mismo gesto.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-006",
    "title": "Mesa congelada",
    "description": "Grabad un vídeo de toda la mesa quedándose congelada durante cinco segundos.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-007",
    "title": "Brindis de mesa",
    "description": "Haced una foto de toda la mesa brindando por los novios.",
    "evidence_type": "photo",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-008",
    "title": "Brindis narrado",
    "description": "Grabad un vídeo con un brindis corto para los novios.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-009",
    "title": "La mesa más coordinada",
    "description": "Grabad un vídeo haciendo un movimiento sincronizado entre todos.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-010",
    "title": "Foto con los novios",
    "description": "Conseguid una foto de alguien de la mesa con los novios.",
    "evidence_type": "photo",
    "category": "Novios",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-011",
    "title": "Consejo matrimonial",
    "description": "Grabad un vídeo con un consejo para los novios.",
    "evidence_type": "video",
    "category": "Novios",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-012",
    "title": "Mensaje secreto",
    "description": "Grabad un vídeo corto dedicando un mensaje sorpresa a los novios.",
    "evidence_type": "video",
    "category": "Novios",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-013",
    "title": "Recuerdo favorito",
    "description": "Grabad un vídeo contando un recuerdo bonito con alguno de los novios.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-014",
    "title": "La foto más bonita",
    "description": "Capturad un momento bonito de la boda desde vuestra mesa.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-015",
    "title": "Declaración grupal",
    "description": "Grabad un vídeo corto diciendo algo bonito a los novios entre todos.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-016",
    "title": "Abrazo colectivo",
    "description": "Haced una foto de la mesa dándose un abrazo o gesto cariñoso.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-017",
    "title": "Foto en la pista",
    "description": "Haced una foto de alguien de la mesa dándolo todo en la pista de baile.",
    "evidence_type": "photo",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-018",
    "title": "Paso imposible",
    "description": "Grabad un vídeo enseñando el paso de baile más raro de la mesa.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-019",
    "title": "Coreografía express",
    "description": "Grabad una coreografía de diez segundos con al menos tres personas.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-020",
    "title": "DJ por un minuto",
    "description": "Grabad un vídeo cantando el estribillo de una canción que debería sonar hoy.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-021",
    "title": "Aliados de otra mesa",
    "description": "Haced una foto con alguien de otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-022",
    "title": "Intercambio de cumplidos",
    "description": "Grabad un vídeo diciendo un cumplido a otra mesa.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-023",
    "title": "Foto con desconocidos",
    "description": "Haced una foto con dos personas invitadas que no estén en vuestra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-024",
    "title": "Reto diplomático",
    "description": "Grabad un vídeo convenciendo a otra mesa para que os anime.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-025",
    "title": "Selfie imposible",
    "description": "Haced una selfie donde salga el mayor número posible de personas de la mesa.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-026",
    "title": "Momento película",
    "description": "Recread una escena dramática o divertida como si fuese una película.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-027",
    "title": "La risa más contagiosa",
    "description": "Grabad un vídeo con la mejor carcajada de la mesa.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-028",
    "title": "Objeto misterioso",
    "description": "Haced una foto del objeto más inesperado que encontréis en la mesa.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-029",
    "title": "Foto de celebración",
    "description": "Haced una foto de la mesa celebrando como si hubiese ganado la Champions.",
    "evidence_type": "photo",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-030",
    "title": "Cántico de campeones",
    "description": "Grabad un vídeo con un cántico inventado para vuestra mesa.",
    "evidence_type": "video",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-031",
    "title": "Entrada triunfal",
    "description": "Grabad un vídeo entrando en plano como estrellas de la fiesta.",
    "evidence_type": "video",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-032",
    "title": "Confeti humano",
    "description": "Haced una foto simulando una celebración épica sin usar confeti real.",
    "evidence_type": "photo",
    "category": "Fiesta",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-033",
    "title": "Detalle del lugar",
    "description": "Haced una foto bonita de un detalle de la decoración o del espacio.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-034",
    "title": "La mesa recomienda",
    "description": "Grabad un vídeo recomendando el mejor momento de la celebración hasta ahora.",
    "evidence_type": "video",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-035",
    "title": "Mini tour",
    "description": "Grabad un vídeo de diez segundos enseñando vuestro rincón favorito del evento.",
    "evidence_type": "video",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-036",
    "title": "Final de película",
    "description": "Grabad un vídeo de despedida para el resumen final del evento.",
    "evidence_type": "video",
    "category": "Resumen",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 120,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-037",
    "title": "Foto de los zapatos",
    "description": "Haced una foto creativa juntando los zapatos de varias personas de la mesa.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-038",
    "title": "Manos arriba",
    "description": "Haced una foto de toda la mesa con las manos arriba como celebración.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-039",
    "title": "Corazones con dedos",
    "description": "Haced una foto formando corazones con las manos para los novios.",
    "evidence_type": "photo",
    "category": "Foto grupal",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-040",
    "title": "La mesa seria",
    "description": "Haced una foto de toda la mesa posando con la cara más seria posible.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-041",
    "title": "La mesa loca",
    "description": "Haced una foto de toda la mesa con la pose más disparatada.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-042",
    "title": "Aplauso sincronizado",
    "description": "Grabad un vídeo de toda la mesa aplaudiendo de forma sincronizada.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-043",
    "title": "Ola de mesa",
    "description": "Grabad un vídeo haciendo una ola de un lado a otro de la mesa.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-044",
    "title": "El brindis silencioso",
    "description": "Grabad un vídeo haciendo un brindis exagerado sin decir una sola palabra.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-045",
    "title": "Retrato del capitán",
    "description": "Haced una foto épica del capitán o capitana de la mesa.",
    "evidence_type": "photo",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-046",
    "title": "El mejor complemento",
    "description": "Haced una foto del complemento más llamativo de la mesa.",
    "evidence_type": "photo",
    "category": "Moda",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-047",
    "title": "Foto con flores",
    "description": "Haced una foto bonita usando flores o decoración floral del evento.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-048",
    "title": "Detalle dulce",
    "description": "Haced una foto del detalle más dulce, bonito o apetecible que encontréis.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-049",
    "title": "La servilleta creativa",
    "description": "Haced una foto usando una servilleta como parte de una composición divertida.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-050",
    "title": "Menú favorito",
    "description": "Grabad un vídeo defendiendo cuál ha sido o será el mejor plato del evento.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-051",
    "title": "Foto de anillos imaginarios",
    "description": "Haced una foto simulando una pedida de mano con anillos imaginarios.",
    "evidence_type": "photo",
    "category": "Novios",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-052",
    "title": "Dedicatoria en vídeo",
    "description": "Grabad una dedicatoria de máximo treinta segundos para los novios.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-053",
    "title": "Canción inventada",
    "description": "Grabad un vídeo cantando una canción inventada para el evento.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-054",
    "title": "Entrevista express",
    "description": "Grabad un vídeo entrevistando a alguien de la mesa con tres preguntas rápidas.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-055",
    "title": "Pronóstico de futuro",
    "description": "Grabad un vídeo prediciendo cómo será la vida de los novios dentro de diez años.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-056",
    "title": "Receta para el amor",
    "description": "Grabad un vídeo con vuestra receta de mesa para una relación feliz.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-057",
    "title": "Tres palabras para los novios",
    "description": "Grabad un vídeo donde cada persona diga una palabra para los novios.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-058",
    "title": "Imitación cariñosa",
    "description": "Grabad un vídeo haciendo una imitación cariñosa y respetuosa de una escena típica de pareja.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-059",
    "title": "Pregunta relámpago",
    "description": "Grabad un vídeo respondiendo rápido a qué hace única esta celebración.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-060",
    "title": "Minuto de aplausos",
    "description": "Grabad un vídeo con el aplauso más entusiasta de vuestra mesa.",
    "evidence_type": "video",
    "category": "Fiesta",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 30,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-061",
    "title": "Baile sentado",
    "description": "Grabad un vídeo bailando sin levantarse de la silla.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-062",
    "title": "Zapateado de mesa",
    "description": "Grabad un vídeo haciendo ritmo con los pies bajo la mesa.",
    "evidence_type": "video",
    "category": "Baile",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-063",
    "title": "Mannequin challenge",
    "description": "Grabad un vídeo de toda la mesa inmóvil como una foto viviente.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-064",
    "title": "Pase de modelos",
    "description": "Grabad un vídeo de tres personas desfilando brevemente junto a la mesa.",
    "evidence_type": "video",
    "category": "Moda",
    "difficulty": "medium",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-065",
    "title": "Vídeo boomerang humano",
    "description": "Grabad un vídeo repitiendo un gesto hacia delante y hacia atrás como un boomerang.",
    "evidence_type": "video",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-066",
    "title": "Cámara lenta épica",
    "description": "Grabad un vídeo simulando una escena épica a cámara lenta.",
    "evidence_type": "video",
    "category": "Vídeo",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-067",
    "title": "Abrazo a otra mesa",
    "description": "Haced una foto de alguien de vuestra mesa abrazando a alguien de otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-068",
    "title": "Firma de alianza",
    "description": "Haced una foto con dos mesas posando como si acabaran de firmar una alianza.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-069",
    "title": "Foto con alguien de staff",
    "description": "Haced una foto amable con alguien del equipo del evento, si está disponible.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-070",
    "title": "Trueque simbólico",
    "description": "Haced una foto intercambiando un objeto simbólico con otra mesa.",
    "evidence_type": "photo",
    "category": "Interacción",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-071",
    "title": "Embajadores de mesa",
    "description": "Grabad un vídeo presentando vuestra mesa a otra mesa como si fuerais embajadores.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 90,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-072",
    "title": "Mensaje de otra mesa",
    "description": "Conseguid que otra mesa grabe un vídeo animando a vuestro equipo.",
    "evidence_type": "video",
    "category": "Interacción",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-073",
    "title": "Foto intergeneracional",
    "description": "Haced una foto con personas de generaciones distintas, si es posible.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-074",
    "title": "Foto de infancia recreada",
    "description": "Recread una foto de infancia imaginaria con poses exageradas.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-075",
    "title": "Mirada al futuro",
    "description": "Haced una foto mirando todos hacia un mismo punto como si vierais el futuro.",
    "evidence_type": "photo",
    "category": "Emotivo",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-076",
    "title": "Promesa de mesa",
    "description": "Grabad un vídeo con una promesa divertida que vuestra mesa cumplirá hoy.",
    "evidence_type": "video",
    "category": "Mesa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-077",
    "title": "Brindis emocional",
    "description": "Grabad un vídeo con un brindis emotivo de máximo veinte segundos.",
    "evidence_type": "video",
    "category": "Emotivo",
    "difficulty": "special",
    "default_points": 25,
    "has_time_limit": true,
    "time_limit_seconds": 60,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-078",
    "title": "Lágrima de felicidad",
    "description": "Haced una foto interpretando una escena dramática de emoción máxima.",
    "evidence_type": "photo",
    "category": "Divertido",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-079",
    "title": "Postal para mañana",
    "description": "Haced una foto que los novios deberían guardar para recordar mañana.",
    "evidence_type": "photo",
    "category": "Resumen",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-080",
    "title": "Foto artística",
    "description": "Haced una foto cuidando encuadre, luz y composición como si fuera de concurso.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-081",
    "title": "Sombra divertida",
    "description": "Haced una foto usando sombras para crear una escena divertida.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-082",
    "title": "Reflejo creativo",
    "description": "Haced una foto usando un reflejo en copa, cristal, espejo o móvil.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-083",
    "title": "Perspectiva imposible",
    "description": "Haced una foto jugando con la perspectiva para crear una ilusión óptica.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "hard",
    "default_points": 20,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-084",
    "title": "Color del evento",
    "description": "Haced una foto donde domine el color principal de la celebración.",
    "evidence_type": "photo",
    "category": "Foto creativa",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-085",
    "title": "Rincón secreto",
    "description": "Haced una foto de un rincón bonito que quizá otros no hayan visto.",
    "evidence_type": "photo",
    "category": "Espacio",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": false,
    "time_limit_seconds": null,
    "question_options": null,
    "question_correct_option": null,
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-086",
    "title": "¿Dónde fue la primera cita de la pareja?",
    "description": "¿Dónde fue la primera cita de la pareja?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "En un restaurante",
      "En la playa",
      "En un concierto",
      "En casa de amigos"
    ],
    "question_correct_option": "En un restaurante",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-087",
    "title": "¿Quién dijo primero te quiero?",
    "description": "¿Quién dijo primero te quiero?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "La novia",
      "El novio",
      "Lo dijeron a la vez",
      "No se acuerdan"
    ],
    "question_correct_option": "La novia",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-088",
    "title": "¿Cuál es el plan favorito de la pareja?",
    "description": "¿Cuál es el plan favorito de la pareja?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Viajar",
      "Cine y manta",
      "Salir a bailar",
      "Cocinar juntos"
    ],
    "question_correct_option": "Viajar",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-089",
    "title": "¿Dónde se prometieron?",
    "description": "¿Dónde se prometieron?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "En un viaje",
      "En casa",
      "En una cena",
      "En la playa"
    ],
    "question_correct_option": "En un viaje",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-090",
    "title": "¿Qué comida les gusta compartir?",
    "description": "¿Qué comida les gusta compartir?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "easy",
    "default_points": 10,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Pizza",
      "Sushi",
      "Tortilla",
      "Pasta"
    ],
    "question_correct_option": "Sushi",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-091",
    "title": "¿Cuál fue su primer viaje juntos?",
    "description": "¿Cuál fue su primer viaje juntos?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "París",
      "Lisboa",
      "Roma",
      "Londres"
    ],
    "question_correct_option": "Lisboa",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-092",
    "title": "¿Quién tarda más en prepararse?",
    "description": "¿Quién tarda más en prepararse?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "La novia",
      "El novio",
      "Depende del día",
      "Empate técnico"
    ],
    "question_correct_option": "El novio",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-093",
    "title": "¿Qué canción representa a la pareja?",
    "description": "¿Qué canción representa a la pareja?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Su canción favorita",
      "La del primer baile",
      "Una de karaoke",
      "Una de viaje"
    ],
    "question_correct_option": "La del primer baile",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-094",
    "title": "¿Qué mascota tendrían?",
    "description": "¿Qué mascota tendrían?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Perro",
      "Gato",
      "Los dos",
      "Ninguna"
    ],
    "question_correct_option": "Perro",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-095",
    "title": "¿Quién es más puntual?",
    "description": "¿Quién es más puntual?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "medium",
    "default_points": 15,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "La novia",
      "El novio",
      "Los dos",
      "Ninguno"
    ],
    "question_correct_option": "La novia",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-096",
    "title": "¿Cuál es su serie de sofá favorita?",
    "description": "¿Cuál es su serie de sofá favorita?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Friends",
      "The Office",
      "La que elijan juntos",
      "Una de misterio"
    ],
    "question_correct_option": "La que elijan juntos",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-097",
    "title": "¿Quién organizó más detalles de la boda?",
    "description": "¿Quién organizó más detalles de la boda?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "La novia",
      "El novio",
      "Ambos",
      "La familia"
    ],
    "question_correct_option": "Ambos",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-098",
    "title": "¿Qué destino sueñan visitar?",
    "description": "¿Qué destino sueñan visitar?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Japón",
      "Nueva York",
      "Islandia",
      "Grecia"
    ],
    "question_correct_option": "Japón",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-099",
    "title": "¿Cuál es el superpoder de la pareja?",
    "description": "¿Cuál es el superpoder de la pareja?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Reírse juntos",
      "Bailar sin parar",
      "Improvisar planes",
      "Cocinar para todos"
    ],
    "question_correct_option": "Reírse juntos",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  },
  {
    "id": "default-100",
    "title": "¿Qué frase les define mejor?",
    "description": "¿Qué frase les define mejor?",
    "evidence_type": "question",
    "category": "Preguntas pareja",
    "difficulty": "special",
    "default_points": 20,
    "has_time_limit": true,
    "time_limit_seconds": 45,
    "question_options": [
      "Equipo siempre",
      "Todo al último minuto",
      "Planazo asegurado",
      "Sí a todo"
    ],
    "question_correct_option": "Equipo siempre",
    "is_active": true,
    "created_at": "",
    "updated_at": ""
  }
];
