// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var EVENT_FIELDS = "id, name, description, type, plan_id, is_demo, created_at, upload_start_time, upload_end_time, reveal_time, expiry_date, timezone, language, max_photos, max_videos, max_audios";
var list_events_default = defineTool({
  name: "list_events",
  title: "List my events",
  description: "List the Revelao events owned by the signed-in account, newest first, with schedule and plan limits.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of events to return."),
    search: z.string().trim().min(1).optional().describe("Optional case-insensitive filter on the event name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select(EVENT_FIELDS).eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const events = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(events, null, 2) }],
      structuredContent: { count: events.length, events }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var EVENT_FIELDS2 = "id, name, description, type, plan_id, is_demo, created_at, upload_start_time, upload_end_time, reveal_time, expiry_date, expiry_redirect_url, timezone, language, country_code, max_photos, max_videos, max_audios, max_video_duration, max_audio_duration, allow_video_recording, allow_audio_recording, allow_image_attachment, allow_video_attachment, allow_photo_deletion, allow_photo_sharing, like_counting_enabled, gallery_view_mode, hide_reveal_date, font_family, font_size, header_style, folder_id";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get the full configuration of one event owned by the signed-in account. Never returns event or admin passwords.",
  inputSchema: {
    event_id: z2.string().uuid().describe("UUID of the event.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").select(EVENT_FIELDS2).eq("id", event_id).eq("owner_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Event not found for this account." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/get-event-media-counts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_event_media_counts_default = defineTool3({
  name: "get_event_media_counts",
  title: "Get event media counts",
  description: "Count the photos, videos and audios uploaded to one event owned by the signed-in account, even before the reveal.",
  inputSchema: {
    event_id: z3.string().uuid().describe("UUID of the event.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: event, error: eventError } = await supabase.from("events").select("id, name").eq("id", event_id).eq("owner_id", ctx.getUserId()).maybeSingle();
    if (eventError) return { content: [{ type: "text", text: eventError.message }], isError: true };
    if (!event) {
      return { content: [{ type: "text", text: "Event not found for this account." }], isError: true };
    }
    const { data, error } = await supabase.rpc("get_event_media_counts", {
      target_event_id: event_id
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = Array.isArray(data) ? data[0] : data;
    const counts = {
      event_id,
      event_name: event.name,
      photo_count: Number(row?.photo_count ?? 0),
      video_count: Number(row?.video_count ?? 0),
      audio_count: Number(row?.audio_count ?? 0)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(counts, null, 2) }],
      structuredContent: counts
    };
  }
});

// src/lib/mcp/tools/update-event-schedule.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var update_event_schedule_default = defineTool4({
  name: "update_event_schedule",
  title: "Update event schedule",
  description: "Update the upload window and/or the reveal time of an event owned by the signed-in account. Timestamps must be ISO 8601 with timezone offset.",
  inputSchema: {
    event_id: z4.string().uuid().describe("UUID of the event."),
    upload_start_time: z4.string().datetime({ offset: true }).optional().describe("New upload window start."),
    upload_end_time: z4.string().datetime({ offset: true }).optional().describe("New upload window end."),
    reveal_time: z4.string().datetime({ offset: true }).optional().describe("New reveal time.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, upload_start_time, upload_end_time, reveal_time }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (upload_start_time) patch.upload_start_time = upload_start_time;
    if (upload_end_time) patch.upload_end_time = upload_end_time;
    if (reveal_time) patch.reveal_time = reveal_time;
    if (Object.keys(patch).length === 0) {
      return {
        content: [{ type: "text", text: "Provide at least one of upload_start_time, upload_end_time or reveal_time." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").update(patch).eq("id", event_id).eq("owner_id", ctx.getUserId()).select("id, name, upload_start_time, upload_end_time, reveal_time").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Event not found for this account." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "towysccybgjyojcxkbkp";
var mcp_default = defineMcp({
  name: "tomorrow-s-album",
  title: "Tomorrow's Album",
  version: "0.1.0",
  instructions: "Tools for Revelao / Tomorrow's Album, the disposable-camera app where guest photos stay hidden until a scheduled reveal. Use `list_events` to find the signed-in owner's events, `get_event` for one event's configuration, `get_event_media_counts` for how much media has been captured, and `update_event_schedule` to move the upload window or reveal time. All tools act as the signed-in user and only see events they own.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, get_event_media_counts_default, update_event_schedule_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
