WITH seed_challenges (
  title,
  description,
  evidence_type,
  category,
  difficulty,
  default_points,
  has_time_limit,
  time_limit_seconds
) AS (
  VALUES
    ('Selfie de bienvenida', 'Haced una selfie de la mesa completa antes de empezar el juego.', 'photo', 'Bienvenida', 'easy', 10, false, NULL),
    ('Nombre de equipo', 'Grabad un audio diciendo el nombre oficial de vuestra mesa y vuestro grito de guerra.', 'audio', 'Bienvenida', 'easy', 10, true, 45),
    ('Pose de portada', 'Haced una foto como si vuestra mesa saliera en la portada de una revista.', 'photo', 'Foto grupal', 'easy', 10, false, NULL),
    ('Foto elegante', 'Haced una foto mostrando el look más elegante de vuestra mesa.', 'photo', 'Foto grupal', 'easy', 10, false, NULL),
    ('Todos a una', 'Haced una foto de toda la mesa haciendo el mismo gesto.', 'photo', 'Foto grupal', 'easy', 10, true, 45),
    ('Mesa congelada', 'Grabad un vídeo de toda la mesa quedándose congelada durante cinco segundos.', 'video', 'Vídeo', 'medium', 15, true, 60),
    ('Brindis de mesa', 'Haced una foto de toda la mesa brindando por los novios.', 'photo', 'Mesa', 'easy', 10, false, NULL),
    ('Brindis narrado', 'Grabad un audio con un brindis corto para los novios.', 'audio', 'Mesa', 'medium', 15, true, 60),
    ('La mesa más coordinada', 'Grabad un vídeo haciendo un movimiento sincronizado entre todos.', 'video', 'Mesa', 'medium', 20, true, 90),
    ('Foto con los novios', 'Conseguid una foto de alguien de la mesa con los novios.', 'photo', 'Novios', 'medium', 20, false, NULL),
    ('Consejo matrimonial', 'Grabad un audio con un consejo para los novios.', 'audio', 'Novios', 'special', 20, true, 90),
    ('Mensaje secreto', 'Grabad un vídeo corto dedicando un mensaje sorpresa a los novios.', 'video', 'Novios', 'special', 25, true, 120),
    ('Recuerdo favorito', 'Grabad un audio contando un recuerdo bonito con alguno de los novios.', 'audio', 'Emotivo', 'special', 20, true, 120),
    ('La foto más bonita', 'Capturad un momento bonito de la boda desde vuestra mesa.', 'photo', 'Emotivo', 'medium', 15, false, NULL),
    ('Declaración grupal', 'Grabad un vídeo corto diciendo algo bonito a los novios entre todos.', 'video', 'Emotivo', 'special', 25, true, 120),
    ('Abrazo colectivo', 'Haced una foto de la mesa dándose un abrazo o gesto cariñoso.', 'photo', 'Emotivo', 'easy', 10, false, NULL),
    ('Foto en la pista', 'Haced una foto de alguien de la mesa dándolo todo en la pista de baile.', 'photo', 'Baile', 'medium', 15, false, NULL),
    ('Paso imposible', 'Grabad un vídeo enseñando el paso de baile más raro de la mesa.', 'video', 'Baile', 'hard', 25, true, 90),
    ('Coreografía express', 'Grabad una coreografía de diez segundos con al menos tres personas.', 'video', 'Baile', 'medium', 20, true, 90),
    ('DJ por un minuto', 'Grabad un audio cantando el estribillo de una canción que debería sonar hoy.', 'audio', 'Baile', 'medium', 15, true, 60),
    ('Aliados de otra mesa', 'Haced una foto con alguien de otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Intercambio de cumplidos', 'Grabad un audio diciendo un cumplido a otra mesa.', 'audio', 'Interacción', 'easy', 10, true, 45),
    ('Foto con desconocidos', 'Haced una foto con dos personas invitadas que no estén en vuestra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Reto diplomático', 'Grabad un vídeo convenciendo a otra mesa para que os anime.', 'video', 'Interacción', 'hard', 25, true, 90),
    ('Selfie imposible', 'Haced una selfie donde salga el mayor número posible de personas de la mesa.', 'photo', 'Divertido', 'easy', 10, true, 60),
    ('Momento película', 'Recread una escena dramática o divertida como si fuese una película.', 'video', 'Divertido', 'hard', 25, true, 120),
    ('La risa más contagiosa', 'Grabad un audio con la mejor carcajada de la mesa.', 'audio', 'Divertido', 'easy', 10, true, 30),
    ('Objeto misterioso', 'Haced una foto del objeto más inesperado que encontréis en la mesa.', 'photo', 'Divertido', 'easy', 10, false, NULL),
    ('Foto de celebración', 'Haced una foto de la mesa celebrando como si hubiese ganado la Champions.', 'photo', 'Fiesta', 'medium', 15, true, 45),
    ('Cántico de campeones', 'Grabad un audio con un cántico inventado para vuestra mesa.', 'audio', 'Fiesta', 'medium', 15, true, 60),
    ('Entrada triunfal', 'Grabad un vídeo entrando en plano como estrellas de la fiesta.', 'video', 'Fiesta', 'medium', 20, true, 90),
    ('Confeti humano', 'Haced una foto simulando una celebración épica sin usar confeti real.', 'photo', 'Fiesta', 'medium', 15, true, 60),
    ('Detalle del lugar', 'Haced una foto bonita de un detalle de la decoración o del espacio.', 'photo', 'Espacio', 'easy', 10, false, NULL),
    ('La mesa recomienda', 'Grabad un audio recomendando el mejor momento de la celebración hasta ahora.', 'audio', 'Espacio', 'medium', 15, true, 60),
    ('Mini tour', 'Grabad un vídeo de diez segundos enseñando vuestro rincón favorito del evento.', 'video', 'Espacio', 'medium', 20, true, 90),
    ('Final de película', 'Grabad un vídeo de despedida para el resumen final del evento.', 'video', 'Resumen', 'special', 25, true, 120),
    ('Foto de los zapatos', 'Haced una foto creativa juntando los zapatos de varias personas de la mesa.', 'photo', 'Foto grupal', 'easy', 10, false, NULL),
    ('Manos arriba', 'Haced una foto de toda la mesa con las manos arriba como celebración.', 'photo', 'Foto grupal', 'easy', 10, true, 45),
    ('Corazones con dedos', 'Haced una foto formando corazones con las manos para los novios.', 'photo', 'Foto grupal', 'easy', 10, false, NULL),
    ('La mesa seria', 'Haced una foto de toda la mesa posando con la cara más seria posible.', 'photo', 'Divertido', 'easy', 10, true, 30),
    ('La mesa loca', 'Haced una foto de toda la mesa con la pose más disparatada.', 'photo', 'Divertido', 'easy', 10, true, 30),
    ('Aplauso sincronizado', 'Grabad un vídeo de toda la mesa aplaudiendo de forma sincronizada.', 'video', 'Mesa', 'medium', 15, true, 60),
    ('Ola de mesa', 'Grabad un vídeo haciendo una ola de un lado a otro de la mesa.', 'video', 'Mesa', 'medium', 15, true, 60),
    ('El brindis silencioso', 'Grabad un vídeo haciendo un brindis exagerado sin decir una sola palabra.', 'video', 'Mesa', 'medium', 15, true, 60),
    ('Retrato del capitán', 'Haced una foto épica del capitán o capitana de la mesa.', 'photo', 'Mesa', 'easy', 10, false, NULL),
    ('El mejor complemento', 'Haced una foto del complemento más llamativo de la mesa.', 'photo', 'Moda', 'easy', 10, false, NULL),
    ('Foto con flores', 'Haced una foto bonita usando flores o decoración floral del evento.', 'photo', 'Espacio', 'easy', 10, false, NULL),
    ('Detalle dulce', 'Haced una foto del detalle más dulce, bonito o apetecible que encontréis.', 'photo', 'Espacio', 'easy', 10, false, NULL),
    ('La servilleta creativa', 'Haced una foto usando una servilleta como parte de una composición divertida.', 'photo', 'Divertido', 'easy', 10, false, NULL),
    ('Menú favorito', 'Grabad un audio defendiendo cuál ha sido o será el mejor plato del evento.', 'audio', 'Mesa', 'easy', 10, true, 45),
    ('Foto de anillos imaginarios', 'Haced una foto simulando una pedida de mano con anillos imaginarios.', 'photo', 'Novios', 'medium', 15, false, NULL),
    ('Dedicatoria en audio', 'Grabad una dedicatoria de máximo treinta segundos para los novios.', 'audio', 'Emotivo', 'medium', 15, true, 30),
    ('Canción inventada', 'Grabad un audio cantando una canción inventada para el evento.', 'audio', 'Audio', 'hard', 20, true, 90),
    ('Entrevista express', 'Grabad un vídeo entrevistando a alguien de la mesa con tres preguntas rápidas.', 'video', 'Vídeo', 'medium', 20, true, 90),
    ('Pronóstico de futuro', 'Grabad un audio prediciendo cómo será la vida de los novios dentro de diez años.', 'audio', 'Emotivo', 'special', 20, true, 90),
    ('Receta para el amor', 'Grabad un audio con vuestra receta de mesa para una relación feliz.', 'audio', 'Emotivo', 'medium', 15, true, 60),
    ('Tres palabras para los novios', 'Grabad un audio donde cada persona diga una palabra para los novios.', 'audio', 'Emotivo', 'easy', 10, true, 60),
    ('Imitación cariñosa', 'Grabad un vídeo haciendo una imitación cariñosa y respetuosa de una escena típica de pareja.', 'video', 'Divertido', 'hard', 25, true, 90),
    ('Pregunta relámpago', 'Grabad un vídeo respondiendo rápido a qué hace única esta celebración.', 'video', 'Vídeo', 'medium', 15, true, 60),
    ('Minuto de aplausos', 'Grabad un audio con el aplauso más entusiasta de vuestra mesa.', 'audio', 'Fiesta', 'easy', 10, true, 30),
    ('Baile sentado', 'Grabad un vídeo bailando sin levantarse de la silla.', 'video', 'Baile', 'medium', 20, true, 60),
    ('Zapateado de mesa', 'Grabad un audio o vídeo haciendo ritmo con los pies bajo la mesa.', 'video', 'Baile', 'medium', 15, true, 45),
    ('Mannequin challenge', 'Grabad un vídeo de toda la mesa inmóvil como una foto viviente.', 'video', 'Vídeo', 'medium', 20, true, 60),
    ('Pase de modelos', 'Grabad un vídeo de tres personas desfilando brevemente junto a la mesa.', 'video', 'Moda', 'medium', 20, true, 90),
    ('Vídeo boomerang humano', 'Grabad un vídeo repitiendo un gesto hacia delante y hacia atrás como un boomerang.', 'video', 'Divertido', 'medium', 15, true, 45),
    ('Cámara lenta épica', 'Grabad un vídeo simulando una escena épica a cámara lenta.', 'video', 'Vídeo', 'hard', 25, true, 90),
    ('Abrazo a otra mesa', 'Haced una foto de alguien de vuestra mesa abrazando a alguien de otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Firma de alianza', 'Haced una foto con dos mesas posando como si acabaran de firmar una alianza.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Foto con alguien de staff', 'Haced una foto amable con alguien del equipo del evento, si está disponible.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Trueque simbólico', 'Haced una foto intercambiando un objeto simbólico con otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL),
    ('Embajadores de mesa', 'Grabad un vídeo presentando vuestra mesa a otra mesa como si fuerais embajadores.', 'video', 'Interacción', 'hard', 25, true, 90),
    ('Mensaje de otra mesa', 'Conseguid que otra mesa grabe un audio animando a vuestro equipo.', 'audio', 'Interacción', 'hard', 20, true, 60),
    ('Foto intergeneracional', 'Haced una foto con personas de generaciones distintas, si es posible.', 'photo', 'Emotivo', 'medium', 15, false, NULL),
    ('Foto de infancia recreada', 'Recread una foto de infancia imaginaria con poses exageradas.', 'photo', 'Divertido', 'medium', 15, false, NULL),
    ('Mirada al futuro', 'Haced una foto mirando todos hacia un mismo punto como si vierais el futuro.', 'photo', 'Emotivo', 'easy', 10, false, NULL),
    ('Promesa de mesa', 'Grabad un audio con una promesa divertida que vuestra mesa cumplirá hoy.', 'audio', 'Mesa', 'medium', 15, true, 60),
    ('Brindis emocional', 'Grabad un vídeo con un brindis emotivo de máximo veinte segundos.', 'video', 'Emotivo', 'special', 25, true, 60),
    ('Lágrima de felicidad', 'Haced una foto interpretando una escena dramática de emoción máxima.', 'photo', 'Divertido', 'easy', 10, true, 45),
    ('Postal para mañana', 'Haced una foto que los novios deberían guardar para recordar mañana.', 'photo', 'Resumen', 'medium', 15, false, NULL),
    ('Foto artística', 'Haced una foto cuidando encuadre, luz y composición como si fuera de concurso.', 'photo', 'Foto creativa', 'medium', 15, false, NULL),
    ('Sombra divertida', 'Haced una foto usando sombras para crear una escena divertida.', 'photo', 'Foto creativa', 'medium', 15, false, NULL),
    ('Reflejo creativo', 'Haced una foto usando un reflejo en copa, cristal, espejo o móvil.', 'photo', 'Foto creativa', 'hard', 20, false, NULL),
    ('Perspectiva imposible', 'Haced una foto jugando con la perspectiva para crear una ilusión óptica.', 'photo', 'Foto creativa', 'hard', 20, false, NULL),
    ('Color del evento', 'Haced una foto donde domine el color principal de la celebración.', 'photo', 'Foto creativa', 'easy', 10, false, NULL),
    ('Rincón secreto', 'Haced una foto de un rincón bonito que quizá otros no hayan visto.', 'photo', 'Espacio', 'medium', 15, false, NULL),
    ('Foto minimalista', 'Haced una foto sencilla y elegante con pocos elementos.', 'photo', 'Foto creativa', 'medium', 15, false, NULL),
    ('Mini documental', 'Grabad un vídeo de quince segundos contando qué está pasando en vuestra mesa.', 'video', 'Vídeo', 'medium', 20, true, 90),
    ('Noticia de última hora', 'Grabad un vídeo narrando una noticia inventada sobre el evento.', 'video', 'Divertido', 'medium', 20, true, 90),
    ('Trailer de la mesa', 'Grabad un tráiler breve presentando vuestra mesa como si fuera una película.', 'video', 'Vídeo', 'hard', 25, true, 120),
    ('Tutorial absurdo', 'Grabad un vídeo explicando un tutorial absurdo relacionado con la fiesta.', 'video', 'Divertido', 'hard', 25, true, 90),
    ('Anuncio publicitario', 'Grabad un vídeo vendiendo vuestra mesa como si fuera el mejor producto del mundo.', 'video', 'Divertido', 'hard', 25, true, 90),
    ('Debate serio', 'Grabad un vídeo debatiendo con máxima seriedad un tema totalmente absurdo.', 'video', 'Divertido', 'medium', 20, true, 90),
    ('El objeto talismán', 'Haced una foto del objeto que representa la suerte de vuestra mesa.', 'photo', 'Mesa', 'easy', 10, false, NULL),
    ('Mascota imaginaria', 'Haced una foto o vídeo presentando la mascota imaginaria de vuestra mesa.', 'video', 'Divertido', 'medium', 20, true, 60),
    ('Superhéroes de mesa', 'Haced una foto posando como superhéroes listos para salvar la fiesta.', 'photo', 'Divertido', 'easy', 10, true, 45),
    ('Villanos elegantes', 'Haced una foto posando como villanos de película, pero con elegancia.', 'photo', 'Divertido', 'easy', 10, true, 45),
    ('La misión secreta', 'Grabad un audio inventando una misión secreta para los novios.', 'audio', 'Divertido', 'medium', 15, true, 60),
    ('Código de mesa', 'Grabad un audio diciendo una contraseña secreta inventada por vuestra mesa.', 'audio', 'Mesa', 'easy', 10, true, 30),
    ('El aplausómetro', 'Grabad un vídeo midiendo quién consigue el aplauso más fuerte de la mesa.', 'video', 'Fiesta', 'medium', 20, true, 60),
    ('Cierre de capitanes', 'Grabad un vídeo final diciendo el nombre de vuestra mesa y despidiéndoos del juego.', 'video', 'Resumen', 'special', 25, true, 120)
)
INSERT INTO public.captains_challenge_catalog (
  title,
  description,
  evidence_type,
  category,
  difficulty,
  default_points,
  has_time_limit,
  time_limit_seconds,
  is_active
)
SELECT
  seed.title,
  seed.description,
  seed.evidence_type,
  seed.category,
  seed.difficulty,
  seed.default_points,
  seed.has_time_limit,
  seed.time_limit_seconds,
  true
FROM seed_challenges seed
WHERE NOT EXISTS (
  SELECT 1
  FROM public.captains_challenge_catalog existing
  WHERE lower(existing.title) = lower(seed.title)
);
