WITH seed_challenges (
  title,
  description,
  evidence_type,
  category,
  difficulty,
  default_points,
  has_time_limit,
  time_limit_seconds,
  question_options,
  question_correct_option
) AS (
  VALUES
    ('Selfie de bienvenida', 'Haced una selfie de la mesa completa antes de empezar el juego.', 'photo', 'Bienvenida', 'easy', 10, false, NULL, NULL, NULL),
    ('Nombre de equipo', 'Grabad un vídeo diciendo el nombre oficial de vuestra mesa y vuestro grito de guerra.', 'video', 'Bienvenida', 'easy', 10, true, 45, NULL, NULL),
    ('Pose de portada', 'Haced una foto como si vuestra mesa saliera en la portada de una revista.', 'photo', 'Foto grupal', 'easy', 10, false, NULL, NULL, NULL),
    ('Foto elegante', 'Haced una foto mostrando el look más elegante de vuestra mesa.', 'photo', 'Foto grupal', 'easy', 10, false, NULL, NULL, NULL),
    ('Todos a una', 'Haced una foto de toda la mesa haciendo el mismo gesto.', 'photo', 'Foto grupal', 'easy', 10, true, 45, NULL, NULL),
    ('Mesa congelada', 'Grabad un vídeo de toda la mesa quedándose congelada durante cinco segundos.', 'video', 'Vídeo', 'medium', 15, true, 60, NULL, NULL),
    ('Brindis de mesa', 'Haced una foto de toda la mesa brindando por los novios.', 'photo', 'Mesa', 'easy', 10, false, NULL, NULL, NULL),
    ('Brindis narrado', 'Grabad un vídeo con un brindis corto para los novios.', 'video', 'Mesa', 'medium', 15, true, 60, NULL, NULL),
    ('La mesa más coordinada', 'Grabad un vídeo haciendo un movimiento sincronizado entre todos.', 'video', 'Mesa', 'medium', 20, true, 90, NULL, NULL),
    ('Foto con los novios', 'Conseguid una foto de alguien de la mesa con los novios.', 'photo', 'Novios', 'medium', 20, false, NULL, NULL, NULL),
    ('Consejo matrimonial', 'Grabad un vídeo con un consejo para los novios.', 'video', 'Novios', 'special', 20, true, 90, NULL, NULL),
    ('Mensaje secreto', 'Grabad un vídeo corto dedicando un mensaje sorpresa a los novios.', 'video', 'Novios', 'special', 25, true, 120, NULL, NULL),
    ('Recuerdo favorito', 'Grabad un vídeo contando un recuerdo bonito con alguno de los novios.', 'video', 'Emotivo', 'special', 20, true, 120, NULL, NULL),
    ('La foto más bonita', 'Capturad un momento bonito de la boda desde vuestra mesa.', 'photo', 'Emotivo', 'medium', 15, false, NULL, NULL, NULL),
    ('Declaración grupal', 'Grabad un vídeo corto diciendo algo bonito a los novios entre todos.', 'video', 'Emotivo', 'special', 25, true, 120, NULL, NULL),
    ('Abrazo colectivo', 'Haced una foto de la mesa dándose un abrazo o gesto cariñoso.', 'photo', 'Emotivo', 'easy', 10, false, NULL, NULL, NULL),
    ('Foto en la pista', 'Haced una foto de alguien de la mesa dándolo todo en la pista de baile.', 'photo', 'Baile', 'medium', 15, false, NULL, NULL, NULL),
    ('Paso imposible', 'Grabad un vídeo enseñando el paso de baile más raro de la mesa.', 'video', 'Baile', 'hard', 25, true, 90, NULL, NULL),
    ('Coreografía express', 'Grabad una coreografía de diez segundos con al menos tres personas.', 'video', 'Baile', 'medium', 20, true, 90, NULL, NULL),
    ('DJ por un minuto', 'Grabad un vídeo cantando el estribillo de una canción que debería sonar hoy.', 'video', 'Baile', 'medium', 15, true, 60, NULL, NULL),
    ('Aliados de otra mesa', 'Haced una foto con alguien de otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Intercambio de cumplidos', 'Grabad un vídeo diciendo un cumplido a otra mesa.', 'video', 'Interacción', 'easy', 10, true, 45, NULL, NULL),
    ('Foto con desconocidos', 'Haced una foto con dos personas invitadas que no estén en vuestra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Reto diplomático', 'Grabad un vídeo convenciendo a otra mesa para que os anime.', 'video', 'Interacción', 'hard', 25, true, 90, NULL, NULL),
    ('Selfie imposible', 'Haced una selfie donde salga el mayor número posible de personas de la mesa.', 'photo', 'Divertido', 'easy', 10, true, 60, NULL, NULL),
    ('Momento película', 'Recread una escena dramática o divertida como si fuese una película.', 'video', 'Divertido', 'hard', 25, true, 120, NULL, NULL),
    ('La risa más contagiosa', 'Grabad un vídeo con la mejor carcajada de la mesa.', 'video', 'Divertido', 'easy', 10, true, 30, NULL, NULL),
    ('Objeto misterioso', 'Haced una foto del objeto más inesperado que encontréis en la mesa.', 'photo', 'Divertido', 'easy', 10, false, NULL, NULL, NULL),
    ('Foto de celebración', 'Haced una foto de la mesa celebrando como si hubiese ganado la Champions.', 'photo', 'Fiesta', 'medium', 15, true, 45, NULL, NULL),
    ('Cántico de campeones', 'Grabad un vídeo con un cántico inventado para vuestra mesa.', 'video', 'Fiesta', 'medium', 15, true, 60, NULL, NULL),
    ('Entrada triunfal', 'Grabad un vídeo entrando en plano como estrellas de la fiesta.', 'video', 'Fiesta', 'medium', 20, true, 90, NULL, NULL),
    ('Confeti humano', 'Haced una foto simulando una celebración épica sin usar confeti real.', 'photo', 'Fiesta', 'medium', 15, true, 60, NULL, NULL),
    ('Detalle del lugar', 'Haced una foto bonita de un detalle de la decoración o del espacio.', 'photo', 'Espacio', 'easy', 10, false, NULL, NULL, NULL),
    ('La mesa recomienda', 'Grabad un vídeo recomendando el mejor momento de la celebración hasta ahora.', 'video', 'Espacio', 'medium', 15, true, 60, NULL, NULL),
    ('Mini tour', 'Grabad un vídeo de diez segundos enseñando vuestro rincón favorito del evento.', 'video', 'Espacio', 'medium', 20, true, 90, NULL, NULL),
    ('Final de película', 'Grabad un vídeo de despedida para el resumen final del evento.', 'video', 'Resumen', 'special', 25, true, 120, NULL, NULL),
    ('Foto de los zapatos', 'Haced una foto creativa juntando los zapatos de varias personas de la mesa.', 'photo', 'Foto grupal', 'easy', 10, false, NULL, NULL, NULL),
    ('Manos arriba', 'Haced una foto de toda la mesa con las manos arriba como celebración.', 'photo', 'Foto grupal', 'easy', 10, true, 45, NULL, NULL),
    ('Corazones con dedos', 'Haced una foto formando corazones con las manos para los novios.', 'photo', 'Foto grupal', 'easy', 10, false, NULL, NULL, NULL),
    ('La mesa seria', 'Haced una foto de toda la mesa posando con la cara más seria posible.', 'photo', 'Divertido', 'easy', 10, true, 30, NULL, NULL),
    ('La mesa loca', 'Haced una foto de toda la mesa con la pose más disparatada.', 'photo', 'Divertido', 'easy', 10, true, 30, NULL, NULL),
    ('Aplauso sincronizado', 'Grabad un vídeo de toda la mesa aplaudiendo de forma sincronizada.', 'video', 'Mesa', 'medium', 15, true, 60, NULL, NULL),
    ('Ola de mesa', 'Grabad un vídeo haciendo una ola de un lado a otro de la mesa.', 'video', 'Mesa', 'medium', 15, true, 60, NULL, NULL),
    ('El brindis silencioso', 'Grabad un vídeo haciendo un brindis exagerado sin decir una sola palabra.', 'video', 'Mesa', 'medium', 15, true, 60, NULL, NULL),
    ('Retrato del capitán', 'Haced una foto épica del capitán o capitana de la mesa.', 'photo', 'Mesa', 'easy', 10, false, NULL, NULL, NULL),
    ('El mejor complemento', 'Haced una foto del complemento más llamativo de la mesa.', 'photo', 'Moda', 'easy', 10, false, NULL, NULL, NULL),
    ('Foto con flores', 'Haced una foto bonita usando flores o decoración floral del evento.', 'photo', 'Espacio', 'easy', 10, false, NULL, NULL, NULL),
    ('Detalle dulce', 'Haced una foto del detalle más dulce, bonito o apetecible que encontréis.', 'photo', 'Espacio', 'easy', 10, false, NULL, NULL, NULL),
    ('La servilleta creativa', 'Haced una foto usando una servilleta como parte de una composición divertida.', 'photo', 'Divertido', 'easy', 10, false, NULL, NULL, NULL),
    ('Menú favorito', 'Grabad un vídeo defendiendo cuál ha sido o será el mejor plato del evento.', 'video', 'Mesa', 'easy', 10, true, 45, NULL, NULL),
    ('Foto de anillos imaginarios', 'Haced una foto simulando una pedida de mano con anillos imaginarios.', 'photo', 'Novios', 'medium', 15, false, NULL, NULL, NULL),
    ('Dedicatoria en vídeo', 'Grabad una dedicatoria de máximo treinta segundos para los novios.', 'video', 'Emotivo', 'medium', 15, true, 30, NULL, NULL),
    ('Canción inventada', 'Grabad un vídeo cantando una canción inventada para el evento.', 'video', 'Vídeo', 'hard', 20, true, 90, NULL, NULL),
    ('Entrevista express', 'Grabad un vídeo entrevistando a alguien de la mesa con tres preguntas rápidas.', 'video', 'Vídeo', 'medium', 20, true, 90, NULL, NULL),
    ('Pronóstico de futuro', 'Grabad un vídeo prediciendo cómo será la vida de los novios dentro de diez años.', 'video', 'Emotivo', 'special', 20, true, 90, NULL, NULL),
    ('Receta para el amor', 'Grabad un vídeo con vuestra receta de mesa para una relación feliz.', 'video', 'Emotivo', 'medium', 15, true, 60, NULL, NULL),
    ('Tres palabras para los novios', 'Grabad un vídeo donde cada persona diga una palabra para los novios.', 'video', 'Emotivo', 'easy', 10, true, 60, NULL, NULL),
    ('Imitación cariñosa', 'Grabad un vídeo haciendo una imitación cariñosa y respetuosa de una escena típica de pareja.', 'video', 'Divertido', 'hard', 25, true, 90, NULL, NULL),
    ('Pregunta relámpago', 'Grabad un vídeo respondiendo rápido a qué hace única esta celebración.', 'video', 'Vídeo', 'medium', 15, true, 60, NULL, NULL),
    ('Minuto de aplausos', 'Grabad un vídeo con el aplauso más entusiasta de vuestra mesa.', 'video', 'Fiesta', 'easy', 10, true, 30, NULL, NULL),
    ('Baile sentado', 'Grabad un vídeo bailando sin levantarse de la silla.', 'video', 'Baile', 'medium', 20, true, 60, NULL, NULL),
    ('Zapateado de mesa', 'Grabad un vídeo haciendo ritmo con los pies bajo la mesa.', 'video', 'Baile', 'medium', 15, true, 45, NULL, NULL),
    ('Mannequin challenge', 'Grabad un vídeo de toda la mesa inmóvil como una foto viviente.', 'video', 'Vídeo', 'medium', 20, true, 60, NULL, NULL),
    ('Pase de modelos', 'Grabad un vídeo de tres personas desfilando brevemente junto a la mesa.', 'video', 'Moda', 'medium', 20, true, 90, NULL, NULL),
    ('Vídeo boomerang humano', 'Grabad un vídeo repitiendo un gesto hacia delante y hacia atrás como un boomerang.', 'video', 'Divertido', 'medium', 15, true, 45, NULL, NULL),
    ('Cámara lenta épica', 'Grabad un vídeo simulando una escena épica a cámara lenta.', 'video', 'Vídeo', 'hard', 25, true, 90, NULL, NULL),
    ('Abrazo a otra mesa', 'Haced una foto de alguien de vuestra mesa abrazando a alguien de otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Firma de alianza', 'Haced una foto con dos mesas posando como si acabaran de firmar una alianza.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Foto con alguien de staff', 'Haced una foto amable con alguien del equipo del evento, si está disponible.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Trueque simbólico', 'Haced una foto intercambiando un objeto simbólico con otra mesa.', 'photo', 'Interacción', 'medium', 15, false, NULL, NULL, NULL),
    ('Embajadores de mesa', 'Grabad un vídeo presentando vuestra mesa a otra mesa como si fuerais embajadores.', 'video', 'Interacción', 'hard', 25, true, 90, NULL, NULL),
    ('Mensaje de otra mesa', 'Conseguid que otra mesa grabe un vídeo animando a vuestro equipo.', 'video', 'Interacción', 'hard', 20, true, 60, NULL, NULL),
    ('Foto intergeneracional', 'Haced una foto con personas de generaciones distintas, si es posible.', 'photo', 'Emotivo', 'medium', 15, false, NULL, NULL, NULL),
    ('Foto de infancia recreada', 'Recread una foto de infancia imaginaria con poses exageradas.', 'photo', 'Divertido', 'medium', 15, false, NULL, NULL, NULL),
    ('Mirada al futuro', 'Haced una foto mirando todos hacia un mismo punto como si vierais el futuro.', 'photo', 'Emotivo', 'easy', 10, false, NULL, NULL, NULL),
    ('Promesa de mesa', 'Grabad un vídeo con una promesa divertida que vuestra mesa cumplirá hoy.', 'video', 'Mesa', 'medium', 15, true, 60, NULL, NULL),
    ('Brindis emocional', 'Grabad un vídeo con un brindis emotivo de máximo veinte segundos.', 'video', 'Emotivo', 'special', 25, true, 60, NULL, NULL),
    ('Lágrima de felicidad', 'Haced una foto interpretando una escena dramática de emoción máxima.', 'photo', 'Divertido', 'easy', 10, true, 45, NULL, NULL),
    ('Postal para mañana', 'Haced una foto que los novios deberían guardar para recordar mañana.', 'photo', 'Resumen', 'medium', 15, false, NULL, NULL, NULL),
    ('Foto artística', 'Haced una foto cuidando encuadre, luz y composición como si fuera de concurso.', 'photo', 'Foto creativa', 'medium', 15, false, NULL, NULL, NULL),
    ('Sombra divertida', 'Haced una foto usando sombras para crear una escena divertida.', 'photo', 'Foto creativa', 'medium', 15, false, NULL, NULL, NULL),
    ('Reflejo creativo', 'Haced una foto usando un reflejo en copa, cristal, espejo o móvil.', 'photo', 'Foto creativa', 'hard', 20, false, NULL, NULL, NULL),
    ('Perspectiva imposible', 'Haced una foto jugando con la perspectiva para crear una ilusión óptica.', 'photo', 'Foto creativa', 'hard', 20, false, NULL, NULL, NULL),
    ('Color del evento', 'Haced una foto donde domine el color principal de la celebración.', 'photo', 'Foto creativa', 'easy', 10, false, NULL, NULL, NULL),
    ('Rincón secreto', 'Haced una foto de un rincón bonito que quizá otros no hayan visto.', 'photo', 'Espacio', 'medium', 15, false, NULL, NULL, NULL),
    ('¿Dónde fue la primera cita de la pareja?', '¿Dónde fue la primera cita de la pareja?', 'question', 'Preguntas pareja', 'easy', 10, true, 45, ARRAY['En un restaurante', 'En la playa', 'En un concierto', 'En casa de amigos']::text[], 'En un restaurante'),
    ('¿Quién dijo primero te quiero?', '¿Quién dijo primero te quiero?', 'question', 'Preguntas pareja', 'easy', 10, true, 45, ARRAY['La novia', 'El novio', 'Lo dijeron a la vez', 'No se acuerdan']::text[], 'La novia'),
    ('¿Cuál es el plan favorito de la pareja?', '¿Cuál es el plan favorito de la pareja?', 'question', 'Preguntas pareja', 'easy', 10, true, 45, ARRAY['Viajar', 'Cine y manta', 'Salir a bailar', 'Cocinar juntos']::text[], 'Viajar'),
    ('¿Dónde se prometieron?', '¿Dónde se prometieron?', 'question', 'Preguntas pareja', 'easy', 10, true, 45, ARRAY['En un viaje', 'En casa', 'En una cena', 'En la playa']::text[], 'En un viaje'),
    ('¿Qué comida les gusta compartir?', '¿Qué comida les gusta compartir?', 'question', 'Preguntas pareja', 'easy', 10, true, 45, ARRAY['Pizza', 'Sushi', 'Tortilla', 'Pasta']::text[], 'Sushi'),
    ('¿Cuál fue su primer viaje juntos?', '¿Cuál fue su primer viaje juntos?', 'question', 'Preguntas pareja', 'medium', 15, true, 45, ARRAY['París', 'Lisboa', 'Roma', 'Londres']::text[], 'Lisboa'),
    ('¿Quién tarda más en prepararse?', '¿Quién tarda más en prepararse?', 'question', 'Preguntas pareja', 'medium', 15, true, 45, ARRAY['La novia', 'El novio', 'Depende del día', 'Empate técnico']::text[], 'El novio'),
    ('¿Qué canción representa a la pareja?', '¿Qué canción representa a la pareja?', 'question', 'Preguntas pareja', 'medium', 15, true, 45, ARRAY['Su canción favorita', 'La del primer baile', 'Una de karaoke', 'Una de viaje']::text[], 'La del primer baile'),
    ('¿Qué mascota tendrían?', '¿Qué mascota tendrían?', 'question', 'Preguntas pareja', 'medium', 15, true, 45, ARRAY['Perro', 'Gato', 'Los dos', 'Ninguna']::text[], 'Perro'),
    ('¿Quién es más puntual?', '¿Quién es más puntual?', 'question', 'Preguntas pareja', 'medium', 15, true, 45, ARRAY['La novia', 'El novio', 'Los dos', 'Ninguno']::text[], 'La novia'),
    ('¿Cuál es su serie de sofá favorita?', '¿Cuál es su serie de sofá favorita?', 'question', 'Preguntas pareja', 'special', 20, true, 45, ARRAY['Friends', 'The Office', 'La que elijan juntos', 'Una de misterio']::text[], 'La que elijan juntos'),
    ('¿Quién organizó más detalles de la boda?', '¿Quién organizó más detalles de la boda?', 'question', 'Preguntas pareja', 'special', 20, true, 45, ARRAY['La novia', 'El novio', 'Ambos', 'La familia']::text[], 'Ambos'),
    ('¿Qué destino sueñan visitar?', '¿Qué destino sueñan visitar?', 'question', 'Preguntas pareja', 'special', 20, true, 45, ARRAY['Japón', 'Nueva York', 'Islandia', 'Grecia']::text[], 'Japón'),
    ('¿Cuál es el superpoder de la pareja?', '¿Cuál es el superpoder de la pareja?', 'question', 'Preguntas pareja', 'special', 20, true, 45, ARRAY['Reírse juntos', 'Bailar sin parar', 'Improvisar planes', 'Cocinar para todos']::text[], 'Reírse juntos'),
    ('¿Qué frase les define mejor?', '¿Qué frase les define mejor?', 'question', 'Preguntas pareja', 'special', 20, true, 45, ARRAY['Equipo siempre', 'Todo al último minuto', 'Planazo asegurado', 'Sí a todo']::text[], 'Equipo siempre')
)
INSERT INTO public.captains_challenge_catalog (
  title,
  description,
  evidence_type,
  category,
  difficulty,
  default_points,
  has_time_limit,
  time_limit_seconds,
  question_options,
  question_correct_option,
  is_active
)
SELECT
  seed.title,
  seed.description,
  seed.evidence_type,
  seed.category,
  seed.difficulty,
  seed.default_points,
  seed.has_time_limit,
  seed.time_limit_seconds,
  seed.question_options,
  seed.question_correct_option,
  true
FROM seed_challenges seed
WHERE NOT EXISTS (
  SELECT 1
  FROM public.captains_challenge_catalog existing
  WHERE lower(existing.title) = lower(seed.title)
);
